config/routes.rb
Reservation::Application.routes.draw do
  resources :lbdds

  get "access/login"

  get "access/menu"

  resources :users

  resources :vipbbsrsbbs

  match 'signup' => 'users#new'

  root :to => 'access#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/vipbbsrsbb.rb
class Vipbbsrsbb < ActiveRecord::Base

	belongs_to :user

	def self.find_section(section="")
		section = Vipbbsrsbb.where(:section => section)
	end

	def self.find_reserve(company="")
		reserve = Vipbbsrsbb.where(:company_name => company)
	end

end

app/controllers/vipbbsrsbbs_controller.rb
class VipbbsrsbbsController < ApplicationController
  # GET /vipbbsrsbbs
  # GET /vipbbsrsbbs.json
  def index
    @vipbbsrsbbs = Vipbbsrsbb.all
    @vipbbsrsbbs = Vipbbsrsbb.where(:section => 'A')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vipbbsrsbbs }
    end
  end

  def index_b
    @vipbbsrsbbs = Vipbbsrsbb.where(:section => 'B')
  end
  def index_c
    @vipbbsrsbbs = Vipbbsrsbb.where(:section => 'C')
  end
  def index_d
    @vipbbsrsbbs = Vipbbsrsbb.where(:section => 'D')
  end
  def index_e
    @vipbbsrsbbs = Vipbbsrsbb.where(:section => 'E')
  end

  # GET /vipbbsrsbbs/1
  # GET /vipbbsrsbbs/1.json
  def show
    @vipbbsrsbb = Vipbbsrsbb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vipbbsrsbb }
    end
  end

  # GET /vipbbsrsbbs/new
  # GET /vipbbsrsbbs/new.json
  def new
    @vipbbsrsbb = Vipbbsrsbb.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vipbbsrsbb }
    end
  end

  # GET /vipbbsrsbbs/1/edit
  def edit
    @vipbbsrsbb = Vipbbsrsbb.find(params[:id])
  end

  # POST /vipbbsrsbbs
  # POST /vipbbsrsbbs.json
  def create
    @vipbbsrsbb = Vipbbsrsbb.new(params[:vipbbsrsbb])

    respond_to do |format|
      if @vipbbsrsbb.save
        format.html { redirect_to @vipbbsrsbb, notice: 'Vipbbsrsbb was successfully created.' }
        format.json { render json: @vipbbsrsbb, status: :created, location: @vipbbsrsbb }
      else
        format.html { render action: "new" }
        format.json { render json: @vipbbsrsbb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vipbbsrsbbs/1
  # PUT /vipbbsrsbbs/1.json
  def update
    @vipbbsrsbb = Vipbbsrsbb.find(params[:id])

    respond_to do |format|
      if @vipbbsrsbb.update_attributes(params[:vipbbsrsbb])
        format.html { redirect_to @vipbbsrsbb, notice: 'Vipbbsrsbb was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vipbbsrsbb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vipbbsrsbbs/1
  # DELETE /vipbbsrsbbs/1.json
  def destroy
    @vipbbsrsbb = Vipbbsrsbb.find(params[:id])
    @vipbbsrsbb.destroy

    respond_to do |format|
      format.html { redirect_to vipbbsrsbbs_url }
      #format.json { head :no_content }
      format.js 
    end
  end

  def visual
    @vipbbsrsbbs_a = Vipbbsrsbb.find_section('A')
    @vipbbsrsbbs_b = Vipbbsrsbb.find_section('B')
    @vipbbsrsbbs_c = Vipbbsrsbb.find_section('C')
    @vipbbsrsbbs_d = Vipbbsrsbb.find_section('D')
    @vipbbsrsbbs_e = Vipbbsrsbb.find_section('E')

    @vipbbsrsbbs_with = Vipbbsrsbb.where(:status => true)
    @vipbbsrsbbs = Vipbbsrsbb.all
    @my_vipbbsrsbbs = Vipbbsrsbb.find_reserve(session[:company_name])
  end

  def update_status
     @vipbbsrsbb = Vipbbsrsbb.find(params[:id])

     respond_to do |format|
      if @vipbbsrsbb.status == false
        if @vipbbsrsbb.update_attribute :status, true
           @vipbbsrsbb.update_attribute :company_name, session[:company_name]
           @vipbbsrsbb.update_attribute :company_contact, session[:company_contact]
           @vipbbsrsbb.update_attribute :company_email, session[:company_email]
          #format.html { redirect_to @vipbbsrsbb, notice: 'Vipbbsrsbb was successfully updated.' }
          #format.json { head :no_content }
          format.js 
        else
          #format.html { render action: "edit" }
          #format.json { render json: @vipbbsrsbb.errors, status: :unprocessable_entity }
        end
      else
        if @vipbbsrsbb.update_attribute :status, false
           @vipbbsrsbb.update_attribute :company_name, nil
           @vipbbsrsbb.update_attribute :company_contact, nil
           @vipbbsrsbb.update_attribute :company_email, nil
          #format.html { redirect_to @vipbbsrsbb, notice: 'Vipbbsrsbb was successfully updated.' }
          #format.json { head :no_content }
           format.js
        else
          #format.html { render action: "edit" }
          #format.json { render json: @vipbbsrsbb.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def logout
    session[:username] = nil
    session[:id] = nil
    session[:company_name] = nil
    session[:company_email] = nil
    session[:company_contact] = nil
    redirect_to :controller => 'access', :action => 'index'
  end

  def my_reserve
    @my_vipbbsrsbbs = Vipbbsrsbb.where(:company_name => session[:company_name])
  end

  def approved
    @vipbbsrsbb = Vipbbsrsbb.find(params[:id])
    @vipbbsrsbb.update_attribute :approved, 'yes'

    respond_to do |format|
      format.html { redirect_to :action => 'visual' }
      UserMailer.send_mail(@vipbbsrsbb.company_email,@vipbbsrsbb.company_name).deliver
      #format.json { head :no_content }
      #format.js 
    end
  end

  def disapproved
     @vipbbsrsbb = Vipbbsrsbb.find(params[:id])
     @vipbbsrsbb.update_attribute :approved, 'no'

    respond_to do |format|
      format.html { redirect_to :action => 'visual' }
      #format.json { head :no_content }
      #format.js 
    end
  end

end

app/helpers/vipbbsrsbbs_helper.rb
module VipbbsrsbbsHelper
end

app/views/vipbbsrsbbs/_form.html.erb
<%= form_for(@vipbbsrsbb) do |f| %>
  <% if @vipbbsrsbb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vipbbsrsbb.errors.count, "error") %> prohibited this vipbbsrsbb from being saved:</h2>

      <ul>
      <% @vipbbsrsbb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_num %><br />
    <%= f.text_field :ticket_num %>
  </div>
  <div class="field">
    <%= f.label :section %><br />
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :company_contact %><br />
    <%= f.text_field :company_contact %>
  </div>
  <div class="field">
    <%= f.label :company_email %><br />
    <%= f.text_field :company_email %>
  </div>
  <div class="field">
    <%= f.hidden_field :flag, :value => 0 %>
    <%= f.select :status, options_for_select([ "false", "true" ]) %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.text_field :approved %>
  </div>


  <div class="actions">
    <%= f.submit('Create Seat') %>
  </div>
<% end %>

app/views/vipbbsrsbbs/approved.js.erb
$(function(){
     $("#vipbbsrsbb_6").click(function(){
		alert(this);
});

app/views/vipbbsrsbbs/destroy.js.erb
$('#<%= dom_id(@vipbbsrsbb) %>').fadeOut();

app/views/vipbbsrsbbs/index.html.erb
<br /><br /><br /><br />
<div class="container">
<h1>VIP BB / SRS BB</h1>
<br />
<ul class="nav-in">
    <li><%= link_to 'Section A', {:controller => 'Vipbbsrsbbs',:action => 'index'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section B', {:controller => 'Vipbbsrsbbs',:action => 'index_b'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section C', {:controller => 'Vipbbsrsbbs',:action => 'index_c'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section D', {:controller => 'Vipbbsrsbbs',:action => 'index_d'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section E', {:controller => 'Vipbbsrsbbs',:action => 'index_e'}, :class => 'btn btn-danger' %></li>
</ul>
<br />
<table class="table table-striped">
  <tr>
    <th>Ticket #</th>
    <th>Company Name</th>
    <th>Contact</th>
    <th>Email</th>
    <th>Approved</th>
    <% if session[:username] == 'admin' %>
        <th></th>
        <th></th>
        <th></th>
    <% end %>   
  </tr>
<% @vipbbsrsbbs.each do |vipbbsrsbb| %>
  <tr id='<%= dom_id vipbbsrsbb %>'>
    <td><%= vipbbsrsbb.ticket_num %></td>
    <td><%= vipbbsrsbb.company_name %></td>
    <td><%= vipbbsrsbb.company_contact %></td>
    <td><%= vipbbsrsbb.company_email %></td>
    <td><%= vipbbsrsbb.approved %></td>
    <% if session[:username] == 'admin' %>
        <td><%= link_to 'Show', vipbbsrsbb %></td>
        <td><%= link_to 'Edit', edit_vipbbsrsbb_path(vipbbsrsbb) %></td>
        <td><%= link_to 'Destroy', vipbbsrsbb, confirm: 'Are you sure?', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if session[:username] == 'admin' %>
    <%= link_to 'New Reservation', {:action => 'new'} ,:class => 'btn btn-primary' %>
<% end %>
<%= link_to 'View', {:controller => 'Vipbbsrsbbs', :action => 'visual'},:class => 'btn btn-primary' %>
</div>

app/views/vipbbsrsbbs/index_b.html.erb
<br /><br /><br /><br />
<div class="container">
<h1>VIP BB / SRS BB</h1>
<br />
<ul class="nav-in">
    <li><%= link_to 'Section A', {:action => 'index'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section B', {:action => 'index_b'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section C', {:action => 'index_c'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section D', {:action => 'index_d'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section E', {:action => 'index_e'}, :class => 'btn btn-danger' %></li>
</ul>
<br />
<table class="table table-striped">
  <tr>
    <th>Ticket #</th>
    <th>Company Name</th>
    <th>Contact</th>
    <th>Email</th>
    <th>Approved</th>
    <% if session[:username] == 'admin' %>
        <th></th>
        <th></th>
        <th></th>
    <% end %>
  </tr>
<% @vipbbsrsbbs.each do |vipbbsrsbb| %>
  <tr id='<%= dom_id vipbbsrsbb %>'>
    <td><%= vipbbsrsbb.ticket_num %></td>
    <td><%= vipbbsrsbb.company_name %></td>
    <td><%= vipbbsrsbb.company_contact %></td>
    <td><%= vipbbsrsbb.company_email %></td>
    <td><%= vipbbsrsbb.status %></td>
    <% if session[:username] == 'admin' %>
        <td><%= link_to 'Show', vipbbsrsbb %></td>
        <td><%= link_to 'Edit', edit_vipbbsrsbb_path(vipbbsrsbb) %></td>
        <td><%= link_to 'Destroy', vipbbsrsbb, confirm: 'Are you sure?', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if session[:username] == 'admin' %>
    <%= link_to 'New Reservation', new_vipbbsrsbb_path,:class => 'btn btn-primary' %>
<% end %>
<%= link_to 'View', {:controller => 'Vipbbsrsbbs', :action => 'visual'},:class => 'btn btn-primary' %>
</div>

app/views/vipbbsrsbbs/index_c.html.erb
<br /><br /><br /><br />
<div class="container">
<h1>VIP BB / SRS BB</h1>
<br />
<ul class="nav-in">
    <li><%= link_to 'Section A', {:action => 'index'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section B', {:action => 'index_b'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section C', {:action => 'index_c'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section D', {:action => 'index_d'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section E', {:action => 'index_e'}, :class => 'btn btn-danger' %></li>
</ul>
<br />
<table class="table table-striped">
  <tr>
    <th>Ticket #</th>
    <th>Company Name</th>
    <th>Contact</th>
    <th>Email</th>
    <th>Approved</th>
    <% if session[:username] == 'admin' %>
        <th></th>
        <th></th>
        <th></th>
    <% end %>
  </tr>
<% @vipbbsrsbbs.each do |vipbbsrsbb| %>
  <tr id='<%= dom_id vipbbsrsbb %>'>
    <td><%= vipbbsrsbb.ticket_num %></td>
    <td><%= vipbbsrsbb.company_name %></td>
    <td><%= vipbbsrsbb.company_contact %></td>
    <td><%= vipbbsrsbb.company_email %></td>
    <td><%= vipbbsrsbb.status %></td>
    <% if session[:username] == 'admin' %>
        <td><%= link_to 'Show', vipbbsrsbb %></td>
        <td><%= link_to 'Edit', edit_vipbbsrsbb_path(vipbbsrsbb) %></td>
        <td><%= link_to 'Destroy', vipbbsrsbb, confirm: 'Are you sure?', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if session[:username] == 'admin' %>
    <%= link_to 'New Reservation', new_vipbbsrsbb_path,:class => 'btn btn-primary' %>
<% end %>
<%= link_to 'View', {:controller => 'Vipbbsrsbbs', :action => 'visual'},:class => 'btn btn-primary' %>
</div>

app/views/vipbbsrsbbs/index_d.html.erb
<br /><br /><br /><br />
<div class="container">
<h1>VIP BB / SRS BB</h1>
<br />
<ul class="nav-in">
    <li><%= link_to 'Section A', {:action => 'index'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section B', {:action => 'index_b'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section C', {:action => 'index_c'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section D', {:action => 'index_d'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section E', {:action => 'index_e'}, :class => 'btn btn-danger' %></li>
</ul>
<br />
<table class="table table-striped">
  <tr>
    <th>Ticket #</th>
    <th>Company Name</th>
    <th>Contact</th>
    <th>Email</th>
    <th>Approved</th>
    <% if session[:username] == 'admin' %>
        <th></th>
        <th></th>
        <th></th>
    <% end %>
  </tr>
<% @vipbbsrsbbs.each do |vipbbsrsbb| %>
  <tr id='<%= dom_id vipbbsrsbb %>'>
    <td><%= vipbbsrsbb.ticket_num %></td>
    <td><%= vipbbsrsbb.company_name %></td>
    <td><%= vipbbsrsbb.company_contact %></td>
    <td><%= vipbbsrsbb.company_email %></td>
    <td><%= vipbbsrsbb.status %></td>
    <% if session[:username] == 'admin' %>
        <td><%= link_to 'Show', vipbbsrsbb %></td>
        <td><%= link_to 'Edit', edit_vipbbsrsbb_path(vipbbsrsbb) %></td>
        <td><%= link_to 'Destroy', vipbbsrsbb, confirm: 'Are you sure?', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if session[:username] == 'admin' %>
    <%= link_to 'New Reservation', new_vipbbsrsbb_path,:class => 'btn btn-primary' %>
<% end %>
<%= link_to 'View', {:controller => 'Vipbbsrsbbs', :action => 'visual'},:class => 'btn btn-primary' %>
</div>

app/views/vipbbsrsbbs/index_e.html.erb
<br /><br /><br /><br />
<div class="container">
<h1>VIP BB / SRS BB</h1>
<br />
<ul class="nav-in">
    <li><%= link_to 'Section A', {:action => 'index'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section B', {:action => 'index_b'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section C', {:action => 'index_c'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section D', {:action => 'index_d'}, :class => 'btn btn-danger' %></li>
    <li><%= link_to 'Section E', {:action => 'index_e'}, :class => 'btn btn-danger' %></li>
</ul>
<br />
<table class="table table-striped">
  <tr>
    <th>Ticket #</th>
    <th>Company Name</th>
    <th>Contact</th>
    <th>Email</th>
    <th>Approved</th>
    <% if session[:username] == 'admin' %>
        <th></th>
        <th></th>
        <th></th>
    <% end %>
  </tr>
<% @vipbbsrsbbs.each do |vipbbsrsbb| %>
  <tr id='<%= dom_id vipbbsrsbb %>'>
    <td><%= vipbbsrsbb.ticket_num %></td>
    <td><%= vipbbsrsbb.company_name %></td>
    <td><%= vipbbsrsbb.company_contact %></td>
    <td><%= vipbbsrsbb.company_email %></td>
    <td><%= vipbbsrsbb.status %></td>
    <% if session[:username] == 'admin' %>
        <td><%= link_to 'Show', vipbbsrsbb %></td>
        <td><%= link_to 'Edit', edit_vipbbsrsbb_path(vipbbsrsbb) %></td>
        <td><%= link_to 'Destroy', vipbbsrsbb, confirm: 'Are you sure?', method: :delete, remote: true %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<% if session[:username] == 'admin' %>
    <%= link_to 'New Reservation', new_vipbbsrsbb_path,:class => 'btn btn-primary' %>
<% end %>
<%= link_to 'View', {:controller => 'Vipbbsrsbbs', :action => 'visual'},:class => 'btn btn-primary' %>
</div>

app/views/vipbbsrsbbs/new.html.erb
<br /><br /><br />
<div class="container">
<h1>New vipbbsrsbb</h1>

<%= render 'form' %>

<%= link_to 'Back', :controller => 'Vipbbsrsbbs',:action => 'index' %>
</div>

app/views/vipbbsrsbbs/show.html.erb
<br /><br /><br />
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <b>Ticket num:</b>
  <%= @vipbbsrsbb.ticket_num %>
</p>
<p>
  <b>Section:</b>
  <%= @vipbbsrsbb.section %>
</p>

<p>
  <b>Company name:</b>
  <%= @vipbbsrsbb.company_name %>
</p>

<p>
  <b>Company contact:</b>
  <%= @vipbbsrsbb.company_contact %>
</p>

<p>
  <b>Company email:</b>
  <%= @vipbbsrsbb.company_email %>
</p>

<p>
  <b>Flag:</b>
  <%= @vipbbsrsbb.flag %>
</p>

<p>
  <b>Status:</b>
  <%= @vipbbsrsbb.status %>
</p>

<p>
  <b>Approved:</b>
  <%= @vipbbsrsbb.approved %>
</p>


<%= link_to 'Edit', edit_vipbbsrsbb_path(@vipbbsrsbb), :class => 'btn btn-primary' %>
<%= link_to 'Back', vipbbsrsbbs_path, :class => 'btn btn-primary' %>
</div>

app/views/vipbbsrsbbs/show_comp.html.erb
<br /><br /><br /><br />
<div class="container">
<p id="notice"><%= notice %></p>


<p>
  <b>Company Name:</b>
  <%= @user.company_name %>
</p>

<p>
  <b>Company Contact:</b>
  <%= @user.company_contact %>
</p>

<p>
  <b>Company Email:</b>
  <%= @user.company_email %>
</p>

<div>
	<p>Reservations</p>
	<p>
		<% @reserves.each do |my| %>
			<%= my.ticket_num %> - <%= my.main_section %><br />
		<% end %>
	</p>
</div>


<%= link_to 'Back', {:action => 'visual'}, :class => 'btn btn-primary' %>
</div>

app/views/vipbbsrsbbs/test.html.erb
<table>
	<tr>
		<td>1</td>
		<td>2</td>
		<td>3</td>
	</tr>
</table>

app/views/vipbbsrsbbs/update_status.js.erb
$(function(){
     $("#<%= dom_id(@vipbbsrsbb) %>").toggleClass('true'); 
     location.reload();     
});

     /*function () {
            $(this).removeClass("true");
            $(this).addClass("false");
            location.reload();
        },
        function () {
            $(this).removeClass("false");
            $(this).addClass("true");
            location.reload();
        });
        */